module.exports = `
    enum unit {
        FOOT
        METER
    }
    input MessageInput {
        content: String
        author: String
    }

    type Message {
        id: ID!
        content: String
        author(length: unit): String
    }

    type Query {
        getMessage(id: ID!): Message
    }

    type Mutation {
        createMessage(input: MessageInput): Message
        updateMessage(id: ID!, input: MessageInput): Message
        deleteMessage(id: ID!): Message
    }
`